FROM apache/airflow:2.9.1

USER root
RUN apt-get update && apt-get install -y git

USER airflow
RUN pip install --no-cache-dir \
    "apache-airflow-providers-amazon==8.19.0" \
    "anthropic==0.40.0"